### ISSUE TITLE
Failure to read a Lua file

### ISSUE THREAD

**Issue by fperrad** [fengari-lua/fengari-node-cli#5]
With my configuration, I obtain a `nodejs` error.

```
$ lsb_release -d
Description:	Ubuntu 17.10
$ nodejs -v
v6.11.4
$ fengari -v
Fengari 0.1.0  Copyright (C) 2017-2018 B. Giannangeli, Daurnimator
Based on: Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
$ cat file.lua 
print 'foo'
$ fengari file.lua 
cannot read file.lua: Unknown encoding: 1024
(node:5600) DeprecationWarning: fs.readSync's legacy String interfaceis deprecated. Use the Buffer API as mentioned in the documentation instead.
```

**Comment by giann** [comment]
I can't reproduce. What did you use to write your file.lua ? Sounds like an odd character is in there.

**Comment by fperrad** [comment]
I created `file.lua` with `vim`.
```
$ hexdump -C file.lua 
00000000  70 72 69 6e 74 20 27 66  6f 6f 27 0a              |print 'foo'.|
0000000c
```

**Comment by fperrad** [comment]
On Travis CI, you exercise only against `node` v8.11.1 & v9.10.1

**Comment by daurnimator** [comment]
Looks like node only gained support for `Uint8Array` in `fs.readSync` in version 7.
See https://nodejs.org/docs/latest-v6.x/api/fs.html#fs_fs_readsync_fd_buffer_offset_length_position vs 
https://nodejs.org/docs/latest-v7.x/api/fs.html#fs_fs_readsync_fd_buffer_offset_length_position

**Comment by daurnimator** [comment]
Test suite passes in node 7.
Test suite has 11 failures in node 6; caused by:
  - Node 6.x not accepting `Uint8Array` to `fs.readSync`
  - `Math.exp` has wrong results:
    ```
    $ nvm exec 7 node -e 'console.log(Math.exp(10))'
    Running node v7.10.1 (npm v4.2.0)
    22026.465794806718
    $ nvm exec 6 node -e 'console.log(Math.exp(10))'
    Running node v6.14.1 (npm v3.10.10)
    22026.46579480671
    ```

**Comment by daurnimator** [comment]
@fperrad will be included in next fengari core point release. fengari-node-cli installed after that point in time will have the bug fixed. Let us know if you find anything else :)
